name: Android Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  ANDROID_COMPILE_SDK: '34'
  ANDROID_BUILD_TOOLS: '34.0.0'
  ANDROID_SDK_TOOLS: '11076708'
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For creating releases
      packages: write  # For uploading release assets
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 'latest'
        accept-android-sdk-licenses: true

    - name: Install Android SDK components
      run: |
        echo 'y' | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'platform-tools' 'platforms;android-34' 'build-tools;34.0.0' 'ndk;25.1.8937393'

    - name: Set up Android environment
      run: |
        echo "${{ secrets.KEYSTORE_PROPERTIES }}" > android/keystore.properties
        echo "${{ secrets.KEYSTORE }}" | base64 -d > android/app/upload-keystore.jks
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --stacktrace

    - name: Build AAB
      run: |
        cd android
        ./gradlew bundleRelease --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: |
          android/app/build/outputs/apk/release/app-release.apk
          android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 7

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: success() 
      with:
        files: |
          android/app/build/outputs/apk/release/app-release.apk
          android/app/build/outputs/bundle/release/app-release.aab
        generate_release_notes: true
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.PAT }}
